# Clan Settings
clans:
  min-name-length: 3
  max-name-length: 16
  min-tag-length: 2
  max-tag-length: 4
  creation-cost: 1000
  max-members-default: 10
  home-teleport-delay: 3
  level-up-multiplier: 1.5

# Database Settings
database:
  host: 185.228.82.169
  port: 3306
  database: s11_SMPClans
  username: u11_1IMZSyQUhi
  password: cnmkYkdZNyREvkSWkbc@=0Ml

# Messages
messages:
  prefix: "&8[&bClans&8]"
  clan-created: "&aSuccesvol clan %clan% aangemaakt!"
  clan-disbanded: "&cClan %clan% is opgeheven!"